# Taps
tap "homebrew/bundle"
tap "neovim/neovim"

# Packages
brew "ack"
brew "autoconf"
brew "automake"
brew "awscli"
brew "ccat"
brew "coreutils"
brew "direnv"
brew "dos2unix"
brew "editorconfig"
brew "gem-completion", args: ["HEAD"]
brew "git"
brew "grc"
brew "imagemagick"
brew "libtool"
brew "neovim"
brew "python"
brew "python3"
brew "reattach-to-user-namespace"
brew "ruby-completion", args: ["HEAD"]
brew "the_silver_searcher"
brew "tidy-html5"
brew "tmux"
brew "tree"
brew "unrar"
brew "unzip"
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "zsh-syntax-highlighting"
