[tools]
node = "24"
pnpm = { version = "latest", os = ["linux"] }
python = "3.12"
tree-sitter = { version = "latest", os = ["linux"] }

[settings]
idiomatic_version_file_enable_tools = ["python", "node"]
auto_install = true
