#!/bin/sh

get_public_ip_cmd=$(curl -s ipinfo.io/ip)

case "$OSTYPE" in
  *darwin*)
    echo $get_public_ip_cmd | pbcopy
    echo "$get_public_ip_cmd copied to paste board!"
    ;;

  *linux*)
    echo $get_public_ip_cmd
    ;;
esac
