#!/bin/sh

case "$1" in
  "-6") # Force IPv6
    get_public_ip_cmd=$(curl -s -6 ifconfig.co)
    ;;
  *)
    get_public_ip_cmd=$(curl -s -4 ifconfig.co)
    ;;
esac

case "$OSTYPE" in
  *darwin*)
    echo $get_public_ip_cmd | pbcopy
    echo "$get_public_ip_cmd copied to paste board!"
    ;;

  *)
    echo $get_public_ip_cmd
    ;;
esac
