#!/bin/sh

case "$1" in
  "-4") # Force IPv4
    get_public_ip_cmd=$(curl -s v4.ifconfig.co)
    ;;
  "-6") # Force IPv6
    get_public_ip_cmd=$(curl -s v6.ifconfig.co)
    ;;
  *)
    get_public_ip_cmd=$(curl -s ifconfig.co)
    ;;
esac

case "$OSTYPE" in
  *darwin*)
    echo $get_public_ip_cmd | pbcopy
    echo "$get_public_ip_cmd copied to paste board!"
    ;;

  *)
    echo $get_public_ip_cmd
    ;;
esac
