return {
  -- "stevearc/conform.nvim",
  -- event = { "BufWritePre" },
  -- cmd = { "ConformInfo" },
  -- keys = {
  --   {
  --     "<leader>F",
  --     function()
  --       require("conform").format({ async = true, lsp_format = "fallback" })
  --     end,
  --     mode = "",
  --     desc = "Format buffer",
  --   },
  -- },
  -- opts = {
  --   formatter_by_ft = {
  --     css = { "prettierd" },
  --     html = { "lsp" },
  --     javascript = { "prettierd" },
  --     javascriptreact = { "prettierd" },
  --     json = { "prettierd" },
  --     lua = { "stylua" },
  --     markdown = { "prettierd" },
  --     python = { "isort", "black" },
  --     scss = { "prettierd" },
  --     sh = { "shfmt" },
  --     svelte = { "prettier", "stylelint" },
  --     typescript = { "prettierd" },
  --     typescriptreact = { "prettierd" },
  --     yaml = { "prettierd" },
  --     zsh = { "beautysh" },
  --   },
  --   -- Set up format-on-save
  --   format_on_save = { timeout_ms = 500, lsp_format = "fallback" },
  --   -- Customize formatters
  --   formatters = {
  --     shfmt = {
  --       prepend_args = { "-i", "2" },
  --     },
  --     svelte_fmt = {
  --       command = "prettier",
  --       args = { "--plugin", "prettier-plugin-svelte", "$FILENAME" },
  --     },
  --   },
  -- },
  -- init = function()
  --   vim.o.formatexpr = "v:lua.require'conform'.formatexpr()"
  -- end,
}
